x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1

  publishedVersion: "1.3.0"
  publishedVersionMetadata:
    releaseNote: >-
      Initial Release
    releaseTypes:
    - Feature
    recommended: true

  images:
    worker:
      properties:
        workers.image.repository:
          type: REPO_WITH_REGISTRY
        workers.image.tag:
          type: TAG
    api:
      properties:
        api.image.repository:
          type: REPO_WITH_REGISTRY
        api.image.tag:
          type: TAG
    dashboard:
      properties:
        dashboard.image.repository:
          type: REPO_WITH_REGISTRY
        dashboard.image.tag:
          type: TAG
    billing:
      properties:
        billing.image.repository:
          type: REPO_WITH_REGISTRY
        billing.image.tag:
          type: TAG
    migrator:
      properties:
        migrator.image.repository:
          type: REPO_WITH_REGISTRY
        migrator.image.tag:
          type: TAG
    templates:
      properties:
        templates.image.repository:
          type: REPO_WITH_REGISTRY
        templates.image.tag:
          type: TAG
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  gcp.project:
    type: string
    default: "myProject"
  gcp.region:
    type: string
    default: "my-region1"
  gcp.zone:
    type: string
    default: "my-region1-a"
  gcp.verify:
    type: boolean
    default: true

required:
- name
- namespace