---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  annotations:
    kubernetes-engine.cloud.google.com/icon: >-
      data:image/png;base64,{{ .Files.Get "logo.png" | b64enc }}
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "plainsight-public", "product_id": "plainsight-k8s-public", "partner_name": "Plainsight"}'
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
spec:
  descriptor:
    type: Plainsight
    version: "1.0.0"
    description: >-
      Plainsight
    maintainers:
    - name: Plainsight
      url: https://plainsight.ai
    links:
    - description: 'User Guide: Google Click to Deploy Plainsight'
      url: https://github.com/sixgill/plainsight-marketplace-deployer/README.md
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}"
  componentKinds:
  - group: apps/v1
    kind: Deployment
  
  - group: v1
    kind: Service
  
  - group: v1
    kind: ConfigMap
  
  - group: v1
    kind: ServiceAccount
  
  - group: batch/v1
    kind: Job