{{- if not .Values.gcp.validate }}
{{- $gcpProject := .Values.gcp.project -}}
{{- $gcpRegion := .Values.gcp.region -}}
---
apiVersion: v1
kind: ConfigMap
data:
  {{- with .Values.storage.blob }}
  BLOB_BUCKET_NAME: {{ .name | default "plainsight-blobs" | quote }}
  BLOB_BUCKET_TYPE: {{ .type | default "gcs" | quote }}
  {{- end }}
  {{- with .Values.storage.download }}
  DOWNLOAD_BUCKET_NAME: {{ .name | default "plainsight-downloads" | quote }}
  DOWNLOAD_BUCKET_TYPE: {{ .type | default "gcs" | quote }}
  {{- end }}
  {{- with .Values.storage.upload }}
  UPLOAD_BUCKET_NAME: {{ .name | default "plainsight-uploads" | quote }}
  UPLOAD_BUCKET_TYPE: {{ .type | default "gcs" | quote }}
  {{- end }}
  BUCKET_CREDS_FILE: {{ .Values.storage.credentials.containerLocalPath | default "/etc/credentials/sa/storage/service-account.json" | quote }}
  EXPIRATION_DAYS: {{ .Values.workers.expirationDays | default 7 | quote }}
  NUM_WORKERS: {{ .Values.workers.numWorkers | default 5 | quote }}
  PUBSUB_TYPE: {{ .Values.workers.pubsubType | default "redis" | quote }}
  REDIS_ADDR: {{ .Values.redis.address | quote }}
  {{- with .Values.email }}
  SENDER_TYPE: {{ .senderType | quote }}
  {{- end }}
  {{- with .Values.workers.smartml }}
  SMARTML_SERVICE_BASE: {{ printf "https://%s-aiplatform.googleapis.com/" $gcpRegion | quote }}
  SMARTML_SERVICE_MAX_WIDTH: {{ .maxWidth | default 500 | quote }}
  SMARTML_SERVICE_PROJECT: {{ $gcpProject | quote }}
  SMARTML_SERVICE_REGION: {{ $gcpRegion | quote }}
  SMARTML_SERVICE_SA_PATH: {{ .credentials.containerLocalPath | default "/etc/credentials/sa/ai/service-account.json" | quote }}
  {{- end }}
  SQL_DIALECT: {{ .Values.database.dialect | default "postgres" | quote }}
  SQL_URL: {{ include "Plainsight.sqlurl" . | quote }}
  {{- with .Values.workers.status }}
  STATUS_BASE: {{ printf "https://%s-ml.googleapis.com/" $gcpRegion | quote }}
  STATUS_CREDENTIALS_SA: {{ .credentials.containerLocalPath | default "/etc/credentials/sa/ai/service-account.json" | quote }}
  {{- end }}
  {{- with .Values.workers.training }}
  TRAINING_CREDENTIALS_SA: {{ .credentials.containerLocalPath | default "/etc/credentials/sa/ai/service-account.json" | quote }}
  TRAINING_IMAGE_URI: {{ .imageURI | quote }}
  TRAINING_PROJECT: {{ $gcpProject | quote }}
  TRAINING_REGION: {{ $gcpRegion | quote }}
  TRAINING_WEBHOOK_ENDPOINT: {{ .webhookEndpoint | quote }}
  {{- end }}
{{- else }}
---
apiVersion: v1
kind: ConfigMap
data:
  IM_HERE: "true"
{{- end }}